### ISSUE TITLE
100 % preview generates warnings to terminal

### ISSUE THREAD

**Issue by jerekupari** [rawstudio/rawstudio#13]
Steps to reproduce:
1. Open rawstudio from the terminal.
2. Open 100 % preview (hotkey '*' or uncheck "Fit to view")
3. Go to next image without leaving 100 %.
4. Leave 100 %:

(rawstudio:7353): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'GtkWidget'

(rawstudio:7353): Gtk-CRITICAL **: gtk_widget_is_drawable: assertion 'GTK_IS_WIDGET (widget)' failed

(rawstudio:7353): GLib-GObject-WARNING **: invalid unclassed pointer in cast to 'GtkWidget'

(rawstudio:7353): Gtk-CRITICAL **: gtk_widget_is_drawable: assertion 'GTK_IS_WIDGET (widget)' failed

is printed in the terminal.
5. From now on _every_ "Fit to view" command generates these warnings. But if you _never_ go to next image while enlarged, the terminal stays quiet.

Tested on git-master 2.1-20160216-983bda1 (self-compiled on Ubuntu 15.10) and Fedora 23 (commit 75ef4c4) in https://github.com/sergiomb2/rawstudio

**Comment by jerekupari** [comment]
This happens similarly all the way back to 2015-02-22 3rd commit (77407a5) (geo support removed by cherry-picking 68b5e43). 

Have not tested farther–and probably won't for now.

**Comment by abrander** [comment]
Thanks for reporting! :-) This should be fixed in 0090676.
