### ISSUE TITLE
Loupe not drawn until dragged

### ISSUE THREAD

**Issue by jerekupari** [rawstudio/rawstudio#14]
The loupe function (Ctrl+left drag on the image preview) stays gray until the mouse is moved after the button press.

**Comment by jerekupari** [comment]
2015-02-24 1416a5d 
Bug is present.

(2015-02-24 9292828 before the massive gtk3 port would not compile)

2015-02-23 68b5e43... Removed geo support (for now).
No bug, loop draws immediately.

**Comment by jerekupari** [comment]
If the bug is in src/rs-loupe.c it must be in that massive gtk3 port (2f7c9fb). There this line
`	g_signal_connect(loupe->canvas, "expose-event", G_CALLBACK(expose), loupe);`
is removed (no other changes). And it sure looks like it could be the culprit, but I don't understand very much about c/gtk/gobject stuff.

What would happen if I just put that line back in there?

**Comment by abrander** [comment]
> `g_signal_connect(loupe->canvas, "expose-event", G_CALLBACK(expose), loupe);`
> What would happen if I just put that line back in there?

This would happen:
`(rawstudio:4651): GLib-GObject-WARNING **: /build/buildd/glib2.0-2.40.2/./gobject/gsignal.c:2462: signal 'expose-event' is invalid for instance '0x20849e0' of type 'GtkDrawingArea'
` :(

I'll try to find a fix.

**Comment by jerekupari** [comment]
Here is something about " “expose-event” signal has been replaced by a new “draw” signal"
https://developer.gnome.org/gtk3/stable/ch25s02.html#id-1.6.3.4.11

Don't know if it's related to this... could not understand very much of it.
