### ISSUE TITLE
100% preview is unusable slow

### ISSUE THREAD

**Issue by abrander** [rawstudio/rawstudio#16]

**Comment by jerekupari** [comment]
I'm pretty sure it was lighting fast before today's fixes. (In the upper left hand corner where it worked...)

________________________________
Lähettäjä: Anders Brander<mailto:notifications@github.com>
Lähetetty: ‎23.‎2.‎2016 1:53
Vastaanottaja: rawstudio/rawstudio<mailto:rawstudio@noreply.github.com>
Aihe: [rawstudio] 100% preview is unusable slow (#16)



---
Reply to this email directly or view it on GitHub:
https://github.com/rawstudio/rawstudio/issues/16

**Comment by jerekupari** [comment]
I just compiled myself a git b6bddc9, and it still is lightning fast. 100 % crop opens in less than a second. (i5-3570K / 8G / 1920x1200 / Nikon D200 images)

**Comment by sergiomb2** [comment]
@jerekupari , I don't understand your comment , so is working? git b6bddc9 is last commit !

**Comment by jerekupari** [comment]
Yes, it is working perfectly fast in my case. 

I thought that maybe Anders uses some filters that have problems, so I just tried to touch every adjustment, but I'm still getting the 100 % crop in less than a second. 

Next I thought that maybe the 10 megapixels of my D200 is not enough to trigger something, but my Lumia 1020's 40 megapixel dngs also enlarge instantly.

**Comment by abrander** [comment]
I'll close this. If this is still relevant, I'm sure we'll hear about it.
