### ISSUE TITLE
The UI problems with GTK+ theming, switch Rawstudio to "System theme"

### ISSUE THREAD

**Issue by sergiomb2** [rawstudio/rawstudio#21]
The UI problems are mostly due to GTK+ theming. You can switch Rawstudio to "System theme" in the preference dialog. That will fix most, if not all, issues.
I have a better experience using "System theme" , IMHO and if it easy we should disable the other options until they got fixed .

**Comment by abrander** [comment]
I think we should keep the option available in master and decide if we will fix it or remove the feature before doing a more formal release.

**Comment by pfrenssen** [comment]
Thanks for the tip, my UI looked broken, and switching to the system theme fixed it.

**Comment by sergiomb2** [comment]
Unfortunately , I see GTK+ theming problems in may others apps , convert gtk2 to gtk3 still not pacific

**Comment by Justinzobel** [comment]
Can someone please advise what gsettings key I need to use to override this by default? I'm wanting to force GTK themeing in the package at Solus.

**Comment by abrander** [comment]
@Justinzobel 

You can set the *gconf* key `/apps/rawstudio/use_system_theme` to `true`.

**Comment by sergiomb2** [comment]
How I default to use system theme ? in the code, when I'm packaging rawstudio

**Comment by abrander** [comment]
@sergiomb2 

Change https://github.com/rawstudio/rawstudio/blob/master/librawstudio/conf_interface.h#L113 to

`#define DEFAULT_CONF_USE_SYSTEM_THEME TRUE`

**Comment by alerque** [comment]
This issue can be closed when #55 is merged.
