### ISSUE TITLE
Remove dcraw loader plugin

### ISSUE THREAD

**Issue by abrander** [rawstudio/rawstudio#24]
dcraw is hard to maintain and becomes less and less relevant.

Removing it would also fix #19.

If we're not removing dcraw, at least we should remove our MMAP_HACK.

**Comment by sergiomb2** [comment]
Remove dcraw is easy , done in : https://github.com/sergiomb2/rawstudio/commit/b47ffb3add43614cb30da22994401d8d1885474d from https://github.com/sergiomb2/rawstudio/tree/devel

**Comment by sergiomb2** [comment]
added to https://github.com/rawstudio/rawstudio/pull/18

**Comment by jerekupari** [comment]
I will try Sergio's Fedora package when I find the time.

What cameras are supported through dcraw? Those that are missing from: https://github.com/klauspost/rawspeed/blob/develop/data/cameras.xml ? The rawspeed support seems to be quite good, couldn't see anything missing there...

**Comment by jerekupari** [comment]
Finally found the little laptop and some time to upgrade it...

Sergio's package works, and fixes the preview issues. But I only tried the Nikon D90 and Canon 5DmII photos that happened to be on that laptop.

But it is still plagued by #7, @abrander did you notice that we wanted to reopen that?

And I find it a bit weird that the Fedora package has git 6643b14 (current rawstudio master) in it's name, but it is actually several commits ahead of that from your own fork. Did you not run the autogen? I noticed myself that the version is not updated, if I just 'make' it without running autogen first.

**Comment by sergiomb2** [comment]
> But it is still plagued by #7 
I think I got that when I choose, photo with "white balance " -> auto , when I choose "white balance" -> Camera , it looks fully correct.

**Comment by jerekupari** [comment]
Auto or camera white balance does not affect my problem.

**Comment by abrander** [comment]
This should be fixed by #33.
