### ISSUE TITLE
What happened to the "Advanced" color profiles?

### ISSUE THREAD

**Issue by jerekupari** [rawstudio/rawstudio#27]
In the early 2.1 development days there used to be "Simple" and "Advanced" color profiles for many cameras. And now there's only Simples left. The differences were quite small, Advanced had mostly more saturation in the most saturated colors (at least for Nikon D90 and D200). 

But, the profiles demanded different white balance settings. And now I guess my old photos have white balances slightly off, because I used the Advanced profiles on them.

Are the Advanced profiles ever coming back, or should I just get the old profile files from an old rawstudio install and add them?

**Comment by abrander** [comment]
I haven't noticed that they were missing as I'm using the profiles from Adobe - but I think you're right.

I wonder when they disappeared? :)

Let's bring them back.

**Comment by jerekupari** [comment]
Ah :)

I think they disappeared about a year ago. I always assumed the dcp profile stuff beginning at 425f5e6 did it. So for a while I used the previous commit to do my work. At 30e4efb the profiles are there, after that haven’t seen them. But haven't tried the commits right after that.

Maybe I should have complained a bit earlier!

**Comment by abrander** [comment]
I believe they disappeared in e9cdb92c.
