### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by jupelius** [rawstudio/rawstudio#30]
The source tree does not compile in Arch Linux with GCC 6.2.1 20160830 and GNU Make 4.2.1.

Steps to reproduce:

clone the repo
run autogen.sh
make

Output of make here http://ix.io/1w78

**Comment by sergiomb2** [comment]
IIRC , I fixed it by removing plugin load-dcraw, it is in https://github.com/rawstudio/rawstudio/pull/18 propose .

**Comment by abrander** [comment]
I believe this was fixed by #33.
