### ISSUE TITLE
Support for newer cameras

### ISSUE THREAD

**Issue by jbuchbinder** [rawstudio/rawstudio#32]
There have been some new cameras which don't have proper rawstudio support; I specifically noticed the Panasonic GH5, but I'm sure that there are others.

It might make sense to migrate in some of the documentation to the github wiki so that users with those models can assist.

**Comment by guzzisti** [comment]
Hi there,

i've moved the old blog post to the [local [(wiki](https://github.com/rawstudio/rawstudio/wiki/Information-about-colour-profiles) and fixed the links where necessary.
Hope this helps others...i was very happy after i found out that the adobe profiles work.

**Comment by abrander** [comment]
Thanks for updating the Wiki, @guzzisti.

This is an ongoing issue - and somewhat related to #53 - I'll close this issue.
