### ISSUE TITLE
Crashes instantly on latest Fedora

### ISSUE THREAD

**Issue by diethardsteiner** [rawstudio/rawstudio#39]
When starting RawStudio it crashes instantly on the latest Fedora version. In the sys log I can only see `killed by SIGSEGV`.

**Comment by sergiomb2** [comment]
do you use fedora rpms ?

**Comment by diethardsteiner** [comment]
yes exactly

**Comment by sergiomb2** [comment]
do you one abrt ? please run gnome-abrt ? have you bugzilla.redhat.com account ? if so use it to open an automatic bug report I will reply there ... , Thanks for the report

**Comment by sergiomb2** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1444739 

```
Truncated backtrace:
Thread no. 1 (3 frames)
 #0 XFlush at Flush.c:38
 #1 rs_curve_size_allocate_helper at rs-curve.c:853
 #2 rs_curve_size_allocate at rs-curve.c:872
```

I will update my system to check this better ... meanwhile you may take a look here : https://fedoraproject.org/wiki/Common_F25_bugs#Wayland_issues , one know workaround is run with 

`export GDK_BACKEND=x11`

can you test it ?

**Comment by diethardsteiner** [comment]
Thanks for the suggestion. I want to use Wayland tough and not switch back
to X11.

**Comment by abrander** [comment]
I'm closing this. If anyone would like to work on Wayland-support, pleases do so.
