### ISSUE TITLE
"Unable to find camera in database, please upload to ftp.rawstudio.org"

### ISSUE THREAD

**Issue by l00z** [rawstudio/rawstudio#41]
Two issues:
Sony ILCA-68 isn't supported and ftp.rawstudio.org doesn't seem to exist anymore. I assume that's the reason my photos are tinted green if I open them in rawstudio.

[Sample RAW](https://github.com/rawstudio/rawstudio/files/1106188/DSC00434.ARW.zip)

Edit: Oh, and I found this error message in rawstudio's terminal output.

**Comment by LebedevRI** [comment]
BTW, there is now an alive raw samples archive: https://raw.pixls.us/, which replaced 'deceased' rawsamples.ch, and it is quite well.
Some posts: https://discuss.pixls.us/t/new-year-new-raw-samples-website/3057 https://discuss.pixls.us/t/keep-the-raws-coming/5223 https://discuss.pixls.us/t/raw-samples-wanted/5420

**Comment by abrander** [comment]
I think this somewhat sad error message will go away when we have fixed #44. I'll close this.
