### ISSUE TITLE
'Export' dialog window appears off screen

### ISSUE THREAD

**Issue by snorkelface** [rawstudio/rawstudio#42]
First of all, I love rawstudio!
The only problem I have is that whenever I select 'export as', the dialog window appears in random locations, sometimes off the visible screen. I tried every window setting and application setting, but I can't solve this.

What's worse, this only happens some times. Sometimes, when I use rawstudio, the window appears in the same location and the same size. Other times, different locations and different size. The behavior is consistent throughout a session.

Kubuntu 14.04, KDE Plasma.

**Comment by abrander** [comment]
I believe this is a GTK+ problem. Maybe even a GTK+ in KDE-land problem. I'm closing.
