### ISSUE TITLE
Vignette tool not working with dng files

### ISSUE THREAD

**Issue by esbante** [rawstudio/rawstudio#45]
I am running the latest build from here and the vignette tool does not seem to be working on .dng files in general (Leica M9 for example) and Pentax .pef files from newer cameras like the Pentax K-1, works on files from the Pentax k-5 though. Is this a known issue?

**Comment by guzzisti** [comment]
Hi there, i can confirm that vignette tool doesn't seem to work with DNG-Files from Pentax K-3II and Pentax MX-1 as well.

**Comment by guzzisti** [comment]
I found that the vignette tool requires a lens to be set. Although the newer Pentax lenses seems not to be identified automatically, you can set this manually. Once set manually, these lens is identified automatically for the other pictures.

According to [this blog](https://rawstudio.org/blog/?p=677) lens support is based on lensfun. Unfortunately i can't find the mentioned "Update Lensfun Database" in the lens library.

**Comment by guzzisti** [comment]
Manually updating the lensfun database in a terminal using `sudo lensfun-update-data` did the trick.

**Comment by guzzisti** [comment]
As editing the wiki is open for everyone, i just added a small "HowTo" for this topic.

**Comment by esbante** [comment]
Nice, works perfectly, thanks!

**Comment by sergiomb2** [comment]
Please I'd like that you test my 3 new commits [1] , specially "readd load-dcraw updated to ufraw-0.22"
if you have feedback please write in issues of the project [2]
[1] https://github.com/sergiomb2/rawstudio/commits/devel
[2] https://github.com/sergiomb2/rawstudio/issues
