### ISSUE TITLE
rawstudio pre-compiling step on Debian 9 (stretch) - configuring issues

### ISSUE THREAD

**Issue by eduardtibet** [rawstudio/rawstudio#46]
Hi!

Here are some issues I faces during running ```./configure``` script on Debian 9 Jessie. For some reasons it doesn't see any ```lcms``` libraries. Maybe the reason is in different version of ```lcms``` installed by default Debian 9 has ```lcms2``` but rawstudio depends on lcms v.1 (???)

I tried just to run find util to find any concerning libraries/headers. So the result is as follows:
```
/usr/lib/x86_64-linux-gnu/pkgconfig/lcms2.pc
/usr/lib/x86_64-linux-gnu/liblcms2.so
/usr/lib/x86_64-linux-gnu/liblcms2.so.2
/usr/lib/x86_64-linux-gnu/liblcms2.so.2.0.8
/usr/lib/x86_64-linux-gnu/gegl-0.3/lcms-from-profile.so
/usr/lib/x86_64-linux-gnu/liblcms.so.1.0.19
/usr/lib/x86_64-linux-gnu/liblcms.so.1
/usr/lib/gimp/2.0/plug-ins/lcms
/usr/lib/gimp/2.0/modules/libdisplay-filter-lcms.so
/usr/lib/i386-linux-gnu/liblcms2.so.2
/usr/lib/i386-linux-gnu/liblcms2.so.2.0.8
/usr/lib/i386-linux-gnu/liblcms.so.1.0.19
/usr/lib/i386-linux-gnu/liblcms.so.1
..
/usr/share/doc-base/lcms-plugin
/usr/share/doc-base/lcms-tutorial
/usr/share/doc-base/lcms-api
/usr/share/doc/liblcms1
/usr/share/doc/liblcms2-utils
/usr/share/doc/liblcms2-2
/usr/share/doc/liblcms2-dev
...
/usr/include/lcms2_plugin.h
/usr/include/lcms2.h
...
```

So seems lcms v.1 headers files don't included by default (and there are no way to install it by default debian way).

if go deeper under debian packaging structure:

```
eduardtibet@xxxxxx:~/zips/rawstudio-2.0$ sudo apt-cache show liblcms2-dev 
Package: liblcms2-dev
Source: lcms2
Version: 2.8-4
Installed-Size: 4928
Maintainer: Thomas Weber <tweber@debian.org>
Architecture: amd64
Replaces: liblcms-dev
Provides: liblcms-dev
Depends: liblcms2-2 (= 2.8-4)
Conflicts: liblcms-dev
```

So it seems that liblcms2-dev is the only library included in Debian 9.

Any ideas how I can configure and then compile rawstudio on D9?

Thanks!

**Comment by sergiomb2** [comment]
rawstudio builds well with   lcms2-devel [1] 

[1]
https://src.fedoraproject.org/cgit/rpms/rawstudio.git/tree/rawstudio.spec#n23

**Comment by eduardtibet** [comment]
The point is why I got the following message despite the fact the liblcms2-dev library is installed (by default debian way - so no need in paths tweaking, etc.)

````
checking for PACKAGE... no
configure: error: Package requirements (gtk+-2.0 >= 2.8.0 libxml-2.0 >= 2.4 gconf-2.0 >= 2.0 lcms dbus-1 exiv2 fftw3f lensfun libcurl flickcurl sqlite3 libssl libgphoto2 x11) were not met:

No package 'lcms' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables PACKAGE_CFLAGS
and PACKAGE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

````

Could you, please, point me where I should to dig in?

Thanks!

**Comment by sergiomb2** [comment]
checking pkg-config is at least version 0.9.0... yes
checking for PACKAGE... yes
checking for GCONF... yes
checking for SQLITE3... yes
checking for LENSFUN... yes
checking for LCMS... yes
checking for LIBGPHOTO2... yes
checking for EXIV2... yes
checking for FFTW3F... yes
checking for DBUS... yes
checking locale.h usability... yes
checking locale.h presence... yes
checking for locale.h... yes
checking for LC_MESSAGES... yes
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking libintl.h usability... yes
checking libintl.h presence... yes
checking for libintl.h... yes
checking for ngettext in libc... yes
checking for dgettext in libc... yes
checking for bind_textdomain_codeset... yes
checking for msgfmt... /usr/bin/msgfmt
checking for dcgettext... yes
checking if msgfmt accepts -c... yes
checking for gmsgfmt... /usr/bin/msgfmt
checking for xgettext... /usr/bin/xgettext
checking for catalogs to be installed...  cs da de en fr it nb pl ru fi es sv nl pt_BR ca hu ja
checking for memmem... yes


are you sure that is lcms   ? 
configure: error:
 Package requirements (gtk+-2.0 >= 2.8.0 libxml-2.0 >= 2.4 gconf-2.0 >= 2.0 lcms dbus-1 exiv2 fftw3f lensfun libcurl flickcurl sqlite3 libssl libgphoto2 x11) were not met ... 
I remember that I can't build it on travis , because travis don't have libgphoto2-2-dev [1] 

[1] https://github.com/sergiomb2/rawstudio/commit/a5c50cd36f7796ada129ee587ec30445adaa779d

**Comment by sergiomb2** [comment]
at beginning : https://github.com/travis-ci/apt-package-whitelist/pull/1949 
after : https://github.com/travis-ci/apt-package-whitelist/issues/2105 
my propose: https://github.com/sergiomb2/apt-package-whitelist/commit/288580240bd8b73767f3890341dc6f65f70ae140 
what travis merged : https://github.com/travis-ci/apt-package-whitelist/commit/016e217ac4aef1c85fa81f54d526b438f86f79d9

**Comment by eduardtibet** [comment]
1. I haven't only ```libgphoto2-dev-doc``` - I installed it but with no overall success. So I don't think this is the main issue.

2. Yes, the problem is at ```lcms```

I attaches my config log: [config.log](https://github.com/rawstudio/rawstudio/files/1632397/config.log)

After some digging (just run in terminal command that return error):

```/usr/bin/pkg-config --exists --print-errors lcms2``` gives no error (return code 0)
but ```/usr/bin/pkg-config --exists --print-errors lcms``` gives error:

```
Package lcms was not found in the pkg-config search path.
Perhaps you should add the directory containing `lcms.pc'
to the PKG_CONFIG_PATH environment variable
No package 'lcms' found
```

So, the problem is in lcms for sure. Some linking (???) issues.

**Comment by eduardtibet** [comment]
And also...

```grep -r lcms```

gives
```
src/gtk-helper.c:#include <lcms.h>
config.log:Package lcms was not found in the pkg-config search path.
config.log:Perhaps you should add the directory containing `lcms.pc'
config.log:No package 'lcms' found
config.log:Package lcms was not found in the pkg-config search path.
config.log:Perhaps you should add the directory containing `lcms.pc'
config.log:No package 'lcms' found
config.log:No package 'lcms' found
config.log:configure:16199: error: Package requirements (gtk+-2.0 >= 2.8.0 libxml-2.0 >= 2.4 gconf-2.0 >= 2.0 lcms dbus-1 exiv2 fftw3f lensfun libcurl flickcurl sqlite3 libssl libgphoto2 x11) were not met:
config.log:No package 'lcms' found
configure.in:pkg_modules="gtk+-2.0 >= 2.8.0 libxml-2.0 >= 2.4 gconf-2.0 >= 2.0 lcms dbus-1 exiv2 fftw3f lensfun libcurl flickcurl sqlite3 libssl libgphoto2 x11"
configure:pkg_modules="gtk+-2.0 >= 2.8.0 libxml-2.0 >= 2.4 gconf-2.0 >= 2.0 lcms dbus-1 exiv2 fftw3f lensfun libcurl flickcurl sqlite3 libssl libgphoto2 x11"
Binary file profiles/sRGB.icc matches
Binary file profiles/generic_camera_profile.icc matches
Binary file profiles/sRGB-linear.icc matches
plugins/load-dcraw/dcraw.cc:#include <lcms.h>
plugins/colorspace-transform/colorspace_transform.c:#include <lcms.h>
plugins/colorspace-transform/colorspace_transform.h:#include <lcms.h>
plugins/colorspace-transform/rs-cmm.c:#include <lcms.h>

```
So I rawstudio can't even import header files with version 2 of lcms ```/usr/include/lcms2.h``` even in case configuring goes well. Of course, symlinking possible, but I don't be sure about inner header structure for v2 is = v1.

**Comment by sergiomb2** [comment]
lcms2-devel contains :
```
/usr/include/lcms2.h
/usr/include/lcms2_plugin.h
/usr/lib/liblcms2.so
/usr/lib/pkgconfig/lcms2.pc
```

**Comment by abrander** [comment]
@eduardtibet 

I just successfully compiled Rawstudio master on a bare Debian 9 image using the following dependencies:

```bash
apt-get -y install gcc make \
	libjpeg62-turbo-dev \
	libtiff5-dev \
	pkg-config \
	liblcms2-dev \
	libglib2.0-dev libgtk-3-dev libxml2-dev \
	libgconf2-dev \
	libsqlite3-dev \
	liblensfun-dev \
	libgphoto2-dev \
	libexiv2-dev \
	libfftw3-dev
```

1. Which version of Rawstudio are you compiling?
2. What is the output of `pkg-config --modversion lcms2 ; pkg-config --libs --cflags`?

**Comment by eduardtibet** [comment]
@abrander,

0. All dependencies, you mentioned above are installed. Except of ```libjpeg62-turbo-dev``` - ```libjpeg8-dev``` was installed instead. I reinstall ```libjpeg62-turbo-dev``` with removing ```libjpeg8-dev``` because of conflicts

```
apt-get --dry-run install gcc make \
>  libjpeg62-turbo-dev \
>  libtiff5-dev \
>  pkg-config \
>  liblcms2-dev \
>  libglib2.0-dev libgtk-3-dev libxml2-dev \
>  libgconf2-dev \
>  libsqlite3-dev \
>  liblensfun-dev \
>  libgphoto2-dev \
>  libexiv2-dev \
>  libfftw3-dev
NOTE: This is only a simulation!
      apt-get needs root privileges for real execution.
      Keep also in mind that locking is deactivated,
      so don't depend on the relevance to the real current situation!
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libxml2-dev is already the newest version (2.9.4+dfsg1-2.2+deb9u1).
libtiff5-dev is already the newest version (4.0.8-2+deb9u1).
libexiv2-dev is already the newest version (0.25-3.1).
libfftw3-dev is already the newest version (3.3.5-3).
gcc is already the newest version (4:6.3.0-4).
libgconf2-dev is already the newest version (3.2.6-4+b1).
libglib2.0-dev is already the newest version (2.50.3-2).
libgtk-3-dev is already the newest version (3.22.11-1).
liblcms2-dev is already the newest version (2.8-4).
liblensfun-dev is already the newest version (0.3.2-3).
libgphoto2-dev is already the newest version (2.5.12-1).
libjpeg62-turbo-dev is already the newest version (1:1.5.1-2).
make is already the newest version (4.1-9.1).
pkg-config is already the newest version (0.29-4+b1).
libsqlite3-dev is already the newest version (3.16.2-5+deb9u1).
``` 

1. rawstudio 2.0 downloaded from here: https://rawstudio.org/files/release/rawstudio-2.0.tar.gz

2.
```
pkg-config --modversion lcms2 
2.8
```

```
pkg-config --libs --cflags lcms2
-llcms2
```

**Comment by sergiomb2** [comment]
>    rawstudio 2.0 downloaded from here: https://rawstudio.org/files/release/rawstudio-2.0.tar.gz

ah , you git master of this branch

**Comment by sergiomb2** [comment]
I download the source like this [1] the generation of hash is done with [2] 

 [1]
```

wget https://github.com/rawstudio/rawstudio/archive/003dd4f33377dcfd15ae32904a7cbb0e92123607/rawstudio-003dd4f.tar.gz to ./rawstudio-003dd4f.tar.gz
cd plugins/load-rawspeed/rawspeed
wget https://github.com/klauspost/rawspeed/archive/fa23d1c2f71c01cc085b80a2a6f8b633edd2626b/rawspeed-fa23d1c.tar.gz to ./rawspeed-fa23d1c.tar.gz
```
[2]
```
#https://github.com/rawstudio/rawstudio/commit/003dd4f33377dcfd15ae32904a7cbb0e92123607
%global commit1 003dd4f33377dcfd15ae32904a7cbb0e92123607
%global shortcommit1 %(c=%{commit1}; echo ${c:0:7})
#https://github.com/klauspost/rawspeed/commit/fa23d1c2f71c01cc085b80a2a6f8b633edd2626b
%global commit2 fa23d1c2f71c01cc085b80a2a6f8b633edd2626b
%global shortcommit2 %(c=%{commit2}; echo ${c:0:7})
Source0:        https://github.com/rawstudio/%{name}/archive/%{commit1}/%{name}-%{shortcommit1}.tar.gz
# cd plugins/load-rawspeed/rawspeed
Source1:        https://github.com/klauspost/rawspeed/archive/%{commit2}/rawspeed-%{shortcommit2}.tar.gz

```

**Comment by eduardtibet** [comment]
BTW, very strange GUI while running - not as shown here (controls, etc.). Is this GUI can be used as reference one for v.2.0? https://cloud.githubusercontent.com/assets/3726205/25037796/60a04078-20fb-11e7-9e17-070a65ba9447.jpg

I have another one with other controls (GTK3?) 
![rawstudio_screenshot_2018-01-16_19-48-05](https://user-images.githubusercontent.com/13361936/35000820-692cb8d6-faf6-11e7-9de8-a8ff042466ab.png)

P.S. Of course, I can make other issue because of different subj, but anyway.

**Comment by sergiomb2** [comment]
https://github.com/rawstudio/rawstudio/issues/21
please switch and use system theme

**Comment by eduardtibet** [comment]
Just found this issue a seconds ago by myself. Thanks!

**Comment by sergiomb2** [comment]
Please I'd like that you test my 3 new commits [1] , specially "readd load-dcraw updated to ufraw-0.22"
if you have feedback please write in issues of the project [2]
[1] https://github.com/sergiomb2/rawstudio/commits/devel
[2] https://github.com/sergiomb2/rawstudio/issues
