### ISSUE TITLE
[feature request] mark modified settings in Tools section

### ISSUE THREAD

**Issue by guzzisti** [rawstudio/rawstudio#47]
When playing around with the settings in the tools section, i can't see with a glance which settings have been change and which has been the default value.
This might not be a big issue for settings where the slider is in the middle by default. Especially temperature and tint shift could use a mark for changed and - if possible - a marker on the slider where the default was.

If made a sample how this could look like (based on my system theme):
![screenshot_2018-01-17_21-01-58](https://user-images.githubusercontent.com/10488791/35064428-54187582-fbca-11e7-95f4-00961d2a64f1.png)

**Comment by abrander** [comment]
This is a nice idea, but to prioritize I'm closing. If anyone would like to work on this, please feel free.
