### ISSUE TITLE
Fedora: what about unbundling Rawspeed and making a shared library?

### ISSUE THREAD

**Issue by Germano0** [rawstudio/rawstudio#6]
Hi, I am the Fedora Darktable package co-mantainer.
Darktable (like Rawstudio) bundles Rawspeed library. Fedora packaging rules [1] do not allow that, so we are discussiing (at [2]) about making a shared library that would be used by both Darktable and Rawstudio.
What do you think about?

[1] https://fedoraproject.org/wiki/Packaging:No_Bundled_Libraries#Copylibs
[2] https://lists.fedoraproject.org/pipermail/packaging/2015-July/010813.html

**Comment by abrander** [comment]
Hi,

It's not easy to unbundle Rawstudio and RawSpeed. Camera support have to be synchronized between the RawSpeed loader and Rawstudio - and right now RawSpeed is nothing but a git-repository with no formal releases.

Btw, We also bundle dcraw (like UFRaw and many other raw converters do) although for different reasons.

What would be possible now is to separate the RawSpeed plugin from the rest of Rawstudio - but that wouldn't make much sense for solving this issue.

To answer your question. If someone succeeds in making RawSpeed into a separate library, I think you'll have to package and maintain n versions of it. (n = number of applications using RawSpeed).

If the needed mechanisms to detect version numbers and camera/file support at runtime gets added to RawSpeed it might be posible, but it'll be somewhat of a development and support burden for upstream.

**Comment by sergiomb2** [comment]
Hi, @abrander at your last sentence , you wrote  "needed mechanisms to detect version numbers and camera/file support at runtime ..." . If I update rawspeed directory (load-rawspeed) to git HEAD (under rawstudio) , Do I need update anything else in rawstudio ? 
Thanks

**Comment by abrander** [comment]
The best answer I can give you is "maybe". RawSpeed makes no promises about API compatibility.

**Comment by sergiomb2** [comment]
doesn't worked 
klauspost/rawspeed/issues/122

**Comment by abrander** [comment]
The issue is covered extensively at the Rawspeed end of things: https://github.com/klauspost/rawspeed/issues/109 - I'll close for now.
