### ISSUE TITLE
Should we re-add load-dcraw plugin ?

### ISSUE THREAD

**Issue by sergiomb2** [rawstudio/rawstudio#64]
First the question, Rawstudio without load-dcraw plugin how will read raw files ? 

Rawstudio uses a copy of ufraw code bundled. Ufraw use dcraw code. 
I updated ufraw to use the latest dcraw code [1] , both projects (ufraw and dcraw) seems inactive for a while , maybe now we should use libraw [5]  .
Fedora packages of ufraw [2] and rawstudio have the ufraw updated code made by be .

load-dcraw plugin is in one branch [3] and the compare is this [4] , if we want re-add this plugin , do you want one PR with all commits or should I squash all commits in one ? 

Thank you. 

[1]
https://github.com/sergiomb2/ufraw/commits/devel_dcraw_9.28

[5]
https://www.libraw.org/

[2]
https://src.fedoraproject.org/rpms/ufraw

[3]
https://github.com/sergiomb2/rawstudio/tree/load-dcraw_9.28

[4]
https://github.com/rawstudio/rawstudio/compare/master...sergiomb2:load-dcraw_9.28

**Comment by abrander** [comment]
I think we should try to do without draw, it's not very maintainer friendly, and really slow. Most modern cameras should be supported by RawSpeed. We have some discussion in #24 and #33.

I think we should update RawSpeed as proposed in #34 thou.

**Comment by abrander** [comment]
I'm closing this for now.
