### ISSUE TITLE
Error duing compiling "StdAfx.h":No such file or directory

### ISSUE THREAD

**Issue by zerglog** [rawstudio/rawstudio#65]
Dear Author:
       I followed the instruction to comilpe on linux. But error appeared "rawstudio-plugin-api.cpp:20:20: fatal error: StdAfx.h: No such file or directory". Could you help me figure out?

**Comment by abrander** [comment]
I'm closing this due to age.

If you're still trying to compile Rawstudio, @zerglog, please attach the output from "make", and re-open this issue.
