### ISSUE TITLE
Crash on opening Fedora gnome 3.36.3 

### ISSUE THREAD

**Issue by gordo52** [rawstudio/rawstudio#66]
Running Fedora Studio   Rawstudio crashes everytime I try to run.  Uninstalled and reinstalled again but no change.  The following was recorded as error. means very little to me as very new

/var/spool/abrt/ccpp-2020-07-04-23:27:12.953614-93184

**Comment by sergiomb2** [comment]
it is a known bug https://bugzilla.redhat.com/show_bug.cgi?id=1444739
can you test with "export GDK_BACKEND=x11"?

**Comment by abrander** [comment]
This looks stale, I'm closing. If you're able to try the suggestion from @sergiomb2, please re-open this issue.
