### ISSUE TITLE
rawstudio crashes at launch on openSuse Leap 15.2, gnome desktop version

### ISSUE THREAD

**Issue by gctillettt** [rawstudio/rawstudio#67]
I installed the rawstudio lib and the rawstudio app on Leap 15.2 with no apparent errors. Then on launch the app doesn't open.
Launched from a terminal the app gives the following: Failed to open file “/usr/share/icons/rawstudio.png”: No such file or directory

Of course, I find that that file does not exist. Otherwise it appears that both the rawstudio lib and rawstudio install without error.
I don't have any great urgency to get this fixed, but I don't think it has been reported.

**Comment by abrander** [comment]
Thanks for reporting this.

How did you install Rawstudio?

**Comment by gctillettt** [comment]
Using Firefox, from the openSUSE site, I executed a search under ‘Software’ for rawstudio (for Leap 15.2). I found two packages to install, Rawstudio and librawstudio-2_1.  I installed librawstudio-2_1 using the ‘Direct Install’ link. Then I installed Rawstudio using the ‘Direct Install’ link. Both packages reported successful installed.  Thanks for the help.  Sent from Mail for Windows 10 From: Anders BranderSent: Wednesday, August 5, 2020 4:30 AMTo: rawstudio/rawstudioCc: gctillettt; AuthorSubject: Re: [rawstudio/rawstudio] rawstudio crashes at launch on openSuse Leap 15.2, gnome desktop version (#67) Thanks for reporting this.How did you install Rawstudio?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by abrander** [comment]
Again thanks for reporting, but I don't think we can do anything about this, as this relies on the packaging done by OpenSUSE. If any OpenSUSE packagers believe this is a problem in Rawstudio itself, they are welcome to re-open this issue, but I will close it for now, as we cannot fix this.

@gctillettt I would suggest reporting this issue with OpenSUSE somehow.
