### ISSUE TITLE
Out of gamut color artifacts in all releases more recent than Ubuntu 16.04

### ISSUE THREAD

**Issue by esbante** [rawstudio/rawstudio#68]
Sometimes colors that clip/burn turn grey, and the borders pixelated. This happens (in some cases) when red is overexposed and blue is underexposed. The problem occurs less with cameras that have original rawstudio support, and more with more recent cameras. With cameras with original rawstudio support this never occurs when using the built in simple color profile, but it sometimes occur (depending on colors in the photo) when using a dcp color profile from adobe camera raw, huelight and other sources. This can be worked around by adjusting the end points of the curve, but the image suffers from it. On cameras that were not supported in rawstudio 2.1, where there are no simple profiles, I think this happens more often. On the Pentax K-1 atleast clipped highlights also turn black.

I do not know if this is related, but when using the vignette tool on a out of gamut/clipped sky the darkened area sometimes turns cyan.

I have tried this on many machines and distros, always with the same effect. In Ubuntu 16.04 this problem only arises with newer cameras, and can be solved just by putting a dot in the curve, anywhere is fine, but in all more recent distributions (ubuntu, fedora, manjaro etc) the problem is there and makes rawstudio unpredictable and difficult to use.

Is there a way to solve this problem?

**Comment by abrander** [comment]
Thanks for reporting this issue.

Do you have a raw file showing the problem you can attach to this issue?

**Comment by esbante** [comment]
I have reverted to Ubuntu 16.04, but I the problem should be there in these two files, one from 5dmk3 and one from Pentax k-1.

https://drive.google.com/file/d/1JB3I3tcP1NveJ-FgUb070JUirSd1owYo/view?usp=sharing

https://drive.google.com/file/d/1RYuq9BHNvGnRp7_j0Pp9I-d3OLUopsiM/view?usp=sharing

**Comment by esbante** [comment]
Did you manage to reproduce it, or should I add some other files?

**Comment by esbante** [comment]
For my use I am perfectly happy with rawstudio in its current state, if it just worked as it should on newer distros. An appimage of rawstudio (14.04 based) should work on any distribution without compatibility problems right? I have tried creating one myself, but unfortunately I haven't been able to make it work. Could that be a way forward?

**Comment by esbante** [comment]
I am back on Manjaro 18 now. The issue is there in the file. You just have to increase exposure and contrast until the red color starts to burn out and turn grey.

**Comment by esbante** [comment]
I just reinstalled my system, now on Manjaro gnome 21.1. In Ubuntu 20.04 the problem persisted. Now, on Manjaro 21.1 it is working exactly as in Ubuntu 16.04 - normal colors, even if under- or overexposed, and DNG files show overexposed areas as black until you add a dot in the curve, then it disappears. Improvement! The vignette tool is not working though, despite sudo update-lensfun-data. Not in dng:s or other raw formats. And as it runs wayland you have to use the "export GDK_BACKEND=x11; rawstudio" command to start it.

**Comment by sergiomb2** [comment]
your sentence is very confuse , if things works as it works on Ubuntu 16.04 is good . if since Ubuntu 16.04  we got an issue. try focus on that ,I don't understand and is very tiring try deduce what happens  between versions ... . Another subject is about wayland (should be reported in other ticket) and yet another subject is len support which stopped because rawspeed and ufraw aren't updated it which is discussed in other issue

**Comment by esbante** [comment]
Yes, you are right, sorry for that. For me, this issue can be closed now, it seems to be resolved (in Manjaro 21.1 atleast. In ubuntu 20.04 it was not, and I do not know if rawstudio has changed, or if there is something concerning the different distributions). This issue is basically the same as the one reported here: https://github.com/sergiomb2/rawstudio/issues/5.
