### ISSUE TITLE
canon 70d image with filter green

### ISSUE THREAD

**Issue by 6mrk9** [rawstudio/rawstudio#8]
if i open a raw with 70d' s have a filter green how isn t possible to remove.

 http://forum.ubuntu-it.org/viewtopic.php?f=73&t=603387

**Comment by sergiomb2** [comment]
You may try my pull request have rawspeed updated , I also fixed a few SIGSEGV with gtk3  (3.18.5) of Fedora 23 , luckily was the first application that crash with that error ... 
https://github.com/rawstudio/rawstudio/pull/11
I should have builds of travis but an error with authorized apt-get, delayed the builds .
https://github.com/sergiomb2/rawstudio/commits/75ef4c445f612aaca87c64c122b8135fd3aa34ab

**Comment by sergiomb2** [comment]
After set my Nikon D3000 simple profile and enable lens, I don't see any problem, have you enable profile and set lens ? (on deselect profile seems that I also had a green filter) .

**Comment by 6mrk9** [comment]
Hi, thank you for the mail, i have dismess to use rawstudio, now i modify
the photo with darktable, have more setting for a better results!
Il 16/Feb/2016 13:51, "Sérgio Basto" <notifications@github.com> ha scritto:

**Comment by abrander** [comment]
Thanks for reporting the issue :-)

This was fixed (along with Canon EOS 6D) in 282e0622.
