### ISSUE TITLE
How about move all bug reports to github, github seems to me a good place  

### ISSUE THREAD

**Issue by sergiomb2** [rawstudio/rawstudio#9]
rawstudio.org it is down for a long time , how about move all bug reports to github ?

**Comment by abrander** [comment]
The idea is great and already prepared. Before rawstudio.org went offline I marked lots of bugs with the "abandon" tag. These bugs should not be moved to Github.

Multiple things need to happen:

- [ ] Bring rawstudio.org back online. We have a complete image ready to boot, but somehow nobody have done it yet.
- [ ] Move everything not marked with "abandon" from Bugzilla to Github.
- [ ] Make Bugzilla read-only.
- [ ] Profit.

**Comment by sergiomb2** [comment]
I just remember one bug report in old bugzilla which was about this new rawstudio , just for point out  we don't need bring rawstudio.org back online

**Comment by alerque** [comment]
What is the status on this? In what ways can "outsiders" pitch in to help? Is the old site image something that can be shared so somebody else can work on getting it back online? Is the old issue repo somewhere we could work on porting relevant issues? Is there any chance of adding some people as co-maintainers on this project so that we can get distro patches applied? This is starting to be a nightmare for package maintainers and is likely to be dropped entirely if there continues to be no motion.

**Comment by sergiomb2** [comment]
in reply of : "Is there any chance of adding some people as co-maintainers on this project so that we can get distro patches applied?" 
Please send patches to my repo ( https://github.com/sergiomb2/rawstudio ) , I'm also a package maintainer and also question myself if I should drop rawstudio . 
I fixed some issues , maybe you like to have it and help me on testing,  co-maintainers are welcome
Regards.

**Comment by abrander** [comment]
I can feel and understand the frustration. Rawstudio is a project maintained by volunteers. Mainly me for the last few years.

To be honest I don't have much time for the project. Rawstudio started almost 10 years ago when we had all the time in the world. Nowadays all maintainers have families and demanding jobs.

I would love a co-maintainer or two who could help with daily stuff.

I still use Rawstudio almost daily, but development has (almost) halted.

I'm not sure how to move forward. I'm tempted to blindly accept #11 without any real testing.

I can fully understand if Rawstudio gets removed from distro repositories - I would be sad thou ;-)

**Comment by sergiomb2** [comment]
Hello , rawstudio failed to build with GCC6 in next Fedora version (24) [1]
the build have https://github.com/rawstudio/rawstudio/pull/11 , looks like it needs update dcraw , and we may also remove some deprecated gtk code ... , we could be low work , I hope . 
 
[1]
https://kojipkgs.fedoraproject.org//work/tasks/727/12880727/build.log

**Comment by sergiomb2** [comment]
@alerque pull was accepted , rawstudio.org still down and we have new bug reports , so we don't need old reports anymore . Closing this issue
